{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hotcodepush",
    "module": "core-android",
    "version": "f61bea30e7834e2fe4c60582657b02cfb226aae3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-android-f61bea30e7834e2fe4c60582657b02cfb226aae3.aar",
          "url": "core-android-f61bea30e7834e2fe4c60582657b02cfb226aae3.aar",
          "size": 457364,
          "sha512": "37d423e09044781d4f8f31085e3c8f04ec2051d8a0d65c294aad66d6fc9c7b779618948a96c3262c7290548773e064f059d71706f6b2ea09459fb2c97fa3bf93",
          "sha256": "18eeeb070d1052a1baffa6640d5e2e648033caba087b35bdbce4fad4b0ad6a75",
          "sha1": "0c880ab22ee45a86917f09cbf1758a63c49b2665",
          "md5": "f73604a873178017483d2eceb4a9e411"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.16.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-android-f61bea30e7834e2fe4c60582657b02cfb226aae3.aar",
          "url": "core-android-f61bea30e7834e2fe4c60582657b02cfb226aae3.aar",
          "size": 457364,
          "sha512": "37d423e09044781d4f8f31085e3c8f04ec2051d8a0d65c294aad66d6fc9c7b779618948a96c3262c7290548773e064f059d71706f6b2ea09459fb2c97fa3bf93",
          "sha256": "18eeeb070d1052a1baffa6640d5e2e648033caba087b35bdbce4fad4b0ad6a75",
          "sha1": "0c880ab22ee45a86917f09cbf1758a63c49b2665",
          "md5": "f73604a873178017483d2eceb4a9e411"
        }
      ]
    }
  ]
}
